# .github/workflows/deploy-to-heroku.yml
name: Deploy to Heroku

on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch the entire history to unshallow the clone

      - name: Create a Deployment
        id: create_deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/deployments \
          -d '{
                "ref": "main",
                "environment": "production",
                "description": "Creating a deployment via workflow",
                "required_contexts": []
              }'

      - name: Set up Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Authenticate with Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "machine git.heroku.com login heroku password $HEROKU_API_KEY" > ~/.netrc

      - name: Add Heroku remote
        run: |
          git remote add heroku https://git.heroku.com/bubble.git

      - name: Push to Heroku
        run: git push heroku main

      - name: Mark Deployment as Success
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DEPLOYMENT_ID=$(curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${{ github.repository }}/deployments | jq -r '.[0].id')
          curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/deployments/$DEPLOYMENT_ID/statuses \
          -d '{
                "state": "success",
                "description": "Deployment to Heroku was successful.",
                "environment_url": "'"$HEROKU_APP_URL"'"
              }'
